### ISSUE TITLE
How to get data in the program?

### ISSUE THREAD

**Issue by chenhengwei1999** [vincrichard/UnsupervisedAnomalyDetection_Timeseries#1]
Excuse me, where do you get the data for this project?

**Comment by vincrichard** [comment]
Hello, this was a school project and the data was provided by Airbus.  
I am sorry because I don't have them anymore. But to be honest even if I had them, I think I would not have the right to share it.
Sorry, hope you can make it work with another dataset.

**Comment by chenhengwei1999** [comment]
OK. I understand that. Thanks for your reply.
